apiVersion: v1
kind: Secret
metadata:
  name: mydb
type: Opaque
data:
  mykey: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: k8s.io/v1
kind: Database
metadata:
  name: mydb
  namespace: default
spec:
  class: db.t2.medium
  engine: postgres
  dbname: mydb
  name: mydb
  deleteprotection: false
  password:
    key: mykey
    name: mydb
  username: postgres
  size: 10