apiVersion: k8s.io/v1
kind: Database
metadata:
  name: mydb
  namespace: default
  labels:
    app: mydb
spec:
  class: db.t2.medium
  engine: postgres
  dbname: mydb
  name: mydb
  deleteprotection: false
  password:
    key: DB_PASSWORD
    name: mydb
  username: postgres
  size: 10